version: '3.9'
services:
  web:
    container_name: line_provider
    build:
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    environment:
      BIND_PORT: ${BIND_PORT}
      BIND_HOST: ${BIND_HOST}
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "${BIND_PORT}:${BIND_PORT}"
    volumes:
      - ./:/code
    networks:
      - betting_network

  rabbitmq:
    container_name: line_provider_rabbitmq
    image: rabbitmq:3.10.7-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    restart: always
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - betting_network

  postgres:
    container_name: line_provider_postgres
    image: library/postgres:16
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DBNAME}
    restart: on-failure
    command: [ "postgres", "-c", "log_statement=none", "-c", "log_destination=stderr" ]
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${PG_USER}", "-d", "${PG_DBNAME}" ]
      interval: 5s
      retries: 5
    networks:
      - betting_network

networks:
  betting_network:
    external: True