"""initial

Revision ID: bfe784ef3685
Revises: 
Create Date: 2024-08-22 21:36:36.716052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bfe784ef3685'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('create schema line_provider')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('status', postgresql.ENUM('WAITING', 'W1', 'W2', name='eventstatusenum', schema='line_provider', inherit_schema=True), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('odds', sa.Numeric(precision=100, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event')),
    schema='line_provider'
    )
    op.create_index(op.f('ix_line_provider_event_id'), 'event', ['id'], unique=False, schema='line_provider')
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute('drop schema line_provider')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_line_provider_event_id'), table_name='event', schema='line_provider')
    op.drop_table('event', schema='line_provider')
    # ### end Alembic commands ###
